### ISSUE TITLE
Technology specific discount rate

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/OSeMOSYS#101]

**Comment by chrwm** [comment]
Hi @willu47 it seems that the technology-specific discount rate was no longer integrated since code version 2015_08_27. (see changelog)

> DiscountRate is no longer technology-specific. Therefore, DiscountRateStorage is now replaced by DiscountRate. In most OSeMOSYS models a single DiscountRate value is applied for all technologies, since data on financing levels for different technologies in different countries/regions is often lacking, a common region-specific (without including technology-specificity) DiscountRate is deemed to be sufficient

I agree that it is difficult to obtain technology-specific data for the discount rate, but the feature could be reintroduced as optional, although the globally defined discount rate could be retained as the default.

**Comment by willu47** [comment]
Implemented in GNU MathProg in OSeMOSYS/OSeMOSYS_GNU_MathProg#65
